### ISSUE TITLE
`zformation_MD` does not give the corresponding formation redshift given the merger redshift

### ISSUE THREAD

**Issue by Steve-Hawk** [kevinturbang/bbh_gwb_time_delay_inference#1]
https://github.com/kevinturbang/bbh_gwb_time_delay_inference/blob/acb102199e9219cc7c3bd2d4543dafb0aa391b97/figures/reproduce_figure_1.ipynb#L78

`formationRates_MD = rateData_MD['formationRates']`. gives $R_*\left(z_f\left(z, t_d\right)\right)$.

According to Eq.(2) of this [paper](http://arxiv.org/abs/2310.17625), the parameter z inside the function `np.power(10, 0.3z)` is the star formation redshift, which should be calculated by a function like `z_at_lookbacktime(lookbacktime(z_merg) + delay_time)` instead of a uniform numpy array from `zformation_MD` (`zformation_MD` basically gives `np.arange(0,10,0.01)`).

**Comment by kevinturbang** [comment]
Hi Xiao-Xiao,

Thank you so much for catching this. This is a very good point. We are currently modifying this and re-running analyses to reflect these changes. We will push new code to the repo as we go along. We'll let you know once everything has been altered. 

Best,
Kevin

**Comment by kevinturbang** [comment]
Dear Xiao-Xiao,

We would like to thank you again for catching this mistake in our code. We repeated all analyses with the correct formation redshift. All notebooks and results have been modified accordingly.

Best regards,
Kevin
